In [2]:
import numpy as np

In [5]:
N = 10
a = np.arange(N)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
np.diag(a)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [14]:
np.sum(a)

45

In [ ]:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [18]:
m = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
l = np.array( [4, 12, -3] )
from numpy import linalg
linalg.solve(m, l)

array([ 0.46666667,  3.84444444, -5.55555556])

In [19]:
np.allclose( np.dot(m, linalg.solve(m, l)), l )

True

In [47]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
np.sum(next_user_stats)
nextLength = np.linalg.norm(next_user_stats)
max_cos = 0
for i in users_stats:
    iLength = np.linalg.norm(i)
    np.sum(i)
    cosine = np.dot( next_user_stats, i ) / ( nextLength * iLength )
#     есть более похожий вектор, но он сделал меньше покупок (я думаю, не стоит его рекомендовать)
#     добавил условие - кол-во покупок у рекомендуемого должно быть больше, чем у нового юзера.
    if np.sum(i) > np.sum(next_user_stats):
#     помогите уйти от if при поиске максимального значения 
        if cosine > max_cos:
            max_cos = cosine
            user = i
print(f'{max_cos}, user - {user}')

0.8451542547285165, user - [1 1 2 1 0 0]
